language: python
matrix:
    include:
        - os: linux
          python: 2.6
          cache: pip
        - os: linux
          python: 2.7
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install pycparser==2.18; pip install unittest2; fi
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests -s -v --with-coverage --cover-package=inotify
after_success:
  - coveralls
